[project]
name = "hackathon-cohort-#3"
authors = []
description = ""
telemetry = true
requirements = []

[contracts.guru]
path = "contracts/guru.clar"
depends_on = []

[contracts.student]
path = "contracts/student.clar"
depends_on = []

[contracts.timely-support]
path = "contracts/timely-support.clar"
depends_on = ["guru", "student"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
